// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV-PZp8tbIMZ37jlIpE241k-LShApWa0w',
    appId: '1:316319349097:web:6ba8fb726f5d38cc96e5f8',
    messagingSenderId: '316319349097',
    projectId: 'autofix-mdt22',
    authDomain: 'autofix-mdt22.firebaseapp.com',
    databaseURL: 'https://autofix-mdt22-default-rtdb.firebaseio.com',
    storageBucket: 'autofix-mdt22.firebasestorage.app',
    measurementId: 'G-KB3YWPMVHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJDCIC8p7Rp26cMblatqZVoH9yfFQXpHw',
    appId: '1:316319349097:android:04589c4efaef067796e5f8',
    messagingSenderId: '316319349097',
    projectId: 'autofix-mdt22',
    databaseURL: 'https://autofix-mdt22-default-rtdb.firebaseio.com',
    storageBucket: 'autofix-mdt22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvbRM8G7mG5VRXf7n2PlAtKeQiS5U-9mQ',
    appId: '1:316319349097:ios:b38881282682c76996e5f8',
    messagingSenderId: '316319349097',
    projectId: 'autofix-mdt22',
    databaseURL: 'https://autofix-mdt22-default-rtdb.firebaseio.com',
    storageBucket: 'autofix-mdt22.firebasestorage.app',
    iosBundleId: 'com.example.autofix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvbRM8G7mG5VRXf7n2PlAtKeQiS5U-9mQ',
    appId: '1:316319349097:ios:b38881282682c76996e5f8',
    messagingSenderId: '316319349097',
    projectId: 'autofix-mdt22',
    databaseURL: 'https://autofix-mdt22-default-rtdb.firebaseio.com',
    storageBucket: 'autofix-mdt22.firebasestorage.app',
    iosBundleId: 'com.example.autofix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV-PZp8tbIMZ37jlIpE241k-LShApWa0w',
    appId: '1:316319349097:web:f13fe15593c528b996e5f8',
    messagingSenderId: '316319349097',
    projectId: 'autofix-mdt22',
    authDomain: 'autofix-mdt22.firebaseapp.com',
    databaseURL: 'https://autofix-mdt22-default-rtdb.firebaseio.com',
    storageBucket: 'autofix-mdt22.firebasestorage.app',
    measurementId: 'G-BWKYJBM07P',
  );
}
